global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "accounts-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['accounts:8080']
  - job_name: "loans-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'loans:8090' ]
  - job_name: "cards-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'cards:9000' ]